// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Bqx1jPeVUf3gJZx7EV8wRVPhsWQtoqo',
    appId: '1:537012624860:web:6e5d3ed236114bebfdc319',
    messagingSenderId: '537012624860',
    projectId: 'loyaltyart-c4a4b',
    authDomain: 'loyaltyart-c4a4b.firebaseapp.com',
    storageBucket: 'loyaltyart-c4a4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy4-6Olg2koeLnMfVw1r4KcsvlgXYUJw0',
    appId: '1:537012624860:android:f61537f24d38c816fdc319',
    messagingSenderId: '537012624860',
    projectId: 'loyaltyart-c4a4b',
    storageBucket: 'loyaltyart-c4a4b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Bqx1jPeVUf3gJZx7EV8wRVPhsWQtoqo',
    appId: '1:537012624860:web:c7daeb4642651cc9fdc319',
    messagingSenderId: '537012624860',
    projectId: 'loyaltyart-c4a4b',
    authDomain: 'loyaltyart-c4a4b.firebaseapp.com',
    storageBucket: 'loyaltyart-c4a4b.firebasestorage.app',
  );
}
